# Generated by Django 5.1.1 on 2024-10-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('branch', models.CharField(choices=[('cse', 'Computer Science and Engineering'), ('ece', 'Electronics and Communication Engineering')], max_length=3)),
                ('subject', models.CharField(choices=[('pfsd', 'Professional Software Development'), ('mswd', 'Mobile Software Development')], max_length=4)),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
